version: "3.8"

services:

  db:
    restart: always
    image: postgres:16.1
    environment:
      POSTGRES_USER: sbu
      POSTGRES_PASSWORD: sbp
      POSTGRES_DB: sb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      # - ./new_database.sql:/docker-entrypoint-initdb.d/new_database.sql
    # network_mode: 'host'
    ports:
      - 5433:5432