version: "3.8"

services:

  db:
    restart: always
    image: postgres:16.1
    environment:
      POSTGRES_USER: sbu
      POSTGRES_PASSWORD: sbp
      POSTGRES_DB: sb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
