# Generated by Django 3.2.15 on 2023-09-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodcartapp', '0075_delete_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.FloatField(blank=True, null=True, verbose_name='расстояние')),
                ('date', models.DateField(verbose_name='дата расчёта расстояния')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='foodcartapp.order', verbose_name='заказ')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='foodcartapp.restaurant', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'расстояние',
                'verbose_name_plural': 'расстояния',
                'ordering': ['interval'],
            },
        ),
    ]
