# Generated by Django 3.2.15 on 2023-09-09 22:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+78887775533', max_length=128, region='RU', verbose_name='телефон'),
        ),
    ]
