# Generated by Django 3.2.15 on 2023-09-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_in_ors', to='foodcartapp.product', verbose_name='товар'),
        ),
    ]
