# Generated by Django 3.2.15 on 2023-09-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_alter_productinorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='price',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.productinorder', verbose_name='цена'),
            preserve_default=False,
        ),
    ]
