# Generated by Django 3.2.15 on 2023-09-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20230919_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='object_id',
        ),
    ]
