# Generated by Django 3.2.15 on 2023-09-19 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20230919_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foodcartapp.product'),
            preserve_default=False,
        ),
    ]
