# Generated by Django 3.2.15 on 2023-09-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_quantity_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name': 'товар и его количество в заказе', 'verbose_name_plural': 'товары и их количество в заказе'},
        ),
    ]
