# Generated by Django 3.2.15 on 2023-09-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_quantity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
