# Generated by Django 3.2.15 on 2023-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_rename_quantity_productinorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Необработанный'), ('1', 'Принят'), ('2', 'Готовится'), ('3', 'Доставляется'), ('3', 'Исполнен')], default=0, max_length=2, verbose_name='статус'),
            preserve_default=False,
        ),
    ]
