# Generated by Django 3.2.15 on 2023-09-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Необработанный'), ('1', 'Принят'), ('2', 'Готовится'), ('3', 'Доставляется'), ('4', 'Исполнен')], db_index=True, max_length=2, verbose_name='статус'),
        ),
    ]
