# Generated by Django 3.2.15 on 2023-09-20 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_auto_20230920_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время звонка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время регистрации'),
        ),
    ]
