# Generated by Django 3.2.15 on 2023-09-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_auto_20230920_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('0', 'Наличностью'), ('1', 'Электронно')], db_index=True, max_length=2, null=True, verbose_name='метод оплаты'),
        ),
    ]
