# Generated by Django 3.2.15 on 2023-09-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0069_alter_order_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
