# Generated by Django 3.2.15 on 2023-09-22 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0070_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.FloatField(verbose_name='расстояние')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='foodcartapp.order', verbose_name='заказ')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='foodcartapp.restaurant', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'расстояние',
                'verbose_name_plural': 'расстояния',
                'ordering': ['interval'],
            },
        ),
    ]
