# Generated by Django 3.2.15 on 2023-09-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0071_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='interval',
            field=models.FloatField(blank=True, null=True, verbose_name='расстояние'),
        ),
    ]
