# Generated by Django 3.2.15 on 2023-09-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0072_alter_distance_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distance',
            options={'verbose_name': 'расстояние', 'verbose_name_plural': 'расстояния'},
        ),
        migrations.RemoveField(
            model_name='distance',
            name='interval',
        ),
    ]
