# Generated by Django 3.2.15 on 2023-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0073_auto_20230924_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distance',
            options={'ordering': ['interval'], 'verbose_name': 'расстояние', 'verbose_name_plural': 'расстояния'},
        ),
        migrations.AddField(
            model_name='distance',
            name='interval',
            field=models.FloatField(blank=True, null=True, verbose_name='расстояние'),
        ),
    ]
