# Generated by Django 3.2.15 on 2023-09-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0074_auto_20230924_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
