# Generated by Django 3.2.15 on 2023-10-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0075_delete_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Координаты доставки: широта (latitude)'),
        ),
        migrations.AddField(
            model_name='order',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Координаты доставки: долгота (longitude)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Координаты ресторана: широта (latitude)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Координаты ресторана: долгота (longitude)'),
        ),
    ]
