# Generated by Django 3.2.15 on 2023-11-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0077_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
    ]
